# Generated by Django 4.2.5 on 2023-11-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_comment_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
    ]
