# Generated by Django 4.2.5 on 2023-11-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
