# Generated by Django 4.2.5 on 2023-11-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_product_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
