# Generated by Django 4.2.5 on 2023-11-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='cards.subcategory', verbose_name='Категории'),
        ),
    ]
